[opencage]
api_key = "279e7ea4b5cc47288801ecd5d5dad428"

google_api_key = "AIzaSyB5d4JGGjheQivbv6yAHMkueVm6yv4M-NY"

[auth]
cookie_name = "rosetta_auth"
cookie_key  = "OhMahFrigginGawdDeborahDidYouSeeThatAcornSquashBetsyBroughtToThanksgiving"
cookie_expiry_days = 30

[security]
# any long random string; used to hash the 6-digit codes
reset_pepper = "q4rnf40rup208345y0273480173-489uqwepdry8jpppppp43807230ruq2085607243y03741-3-84y5"

[postgres]
host = "db.oytqodspgdjehieuzywa.supabase.co"
port = 5432
database = "postgres"
user = "postgres"
password = "$ingletonL0gicCryptex"



[supabase]
url = "https://oytqodspgdjehieuzywa.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95dHFvZHNwZ2RqZWhpZXV6eXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MTQ4MzYsImV4cCI6MjA3MzI5MDgzNn0.OyPN-HUmMcCq5OyP7xECIfsy74AXjtYD7xLsJbV_Pww"
service_role = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95dHFvZHNwZ2RqZWhpZXV6eXdhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzcxNDgzNiwiZXhwIjoyMDczMjkwODM2fQ.VL8meharKK9En5JwNPgyXX9l93fITTczM8XJPMc0Lbc"